/**
 * avatar-player.js
 *
 * Lightweight avatar animation player.
 * Plays a pre-rendered video of the avatar animation in sync with the
 * session playback timeline. Works on both PWA and iOS (file://) builds.
 *
 * Supported formats (tried in order):
 *   1. avatar-animation.mp4  — generated by CI (render-frames.cjs + ffmpeg)
 *   2. avatar-animation.webm — generated locally via render-page.html in Chrome
 */
(() => {
  const VIDEO_SOURCES = [
    "media/avatar/avatar-animation.mp4",
    "media/avatar/avatar-animation.webm",
  ];
  const PLAY_DRIFT_TOLERANCE_SEC = 1.0;
  const PAUSE_DRIFT_TOLERANCE_SEC = 0.04;
  const MAX_PLAYBACK_RATE = 1.08;
  const MIN_PLAYBACK_RATE = 0.92;

  class AvatarPlayer {
    constructor() {
      this.video = null;
      this.stage = null;
      this.message = null;
      this.ready = false;
      this.playbackDurationSec = 1;
      this._lastSeekSec = -1;
      this._lastTargetSec = 0;
      this._isPlaying = false;
      this._pendingSeekSec = null;
    }

    init({ stage, message }) {
      this.stage = stage;
      this.message = message;
      return this._tryLoad(VIDEO_SOURCES, 0);
    }

    _tryLoad(sources, index) {
      if (index >= sources.length) {
        // All formats failed
        if (this.message) {
          this.message.hidden = false;
          const t = this.message.querySelector("strong");
          const d = this.message.querySelector("em");
          if (t) t.textContent = "아바타 영상 로드 실패";
          if (d) d.textContent = "mp4 또는 webm 파일이 필요합니다.";
        }
        return Promise.reject(new Error("Avatar video not found (tried mp4, webm)"));
      }

      return new Promise((resolve, reject) => {
        const video = document.createElement("video");
        video.src = sources[index];
        video.muted = true;
        video.playsInline = true;
        video.setAttribute("playsinline", "");
        video.setAttribute("webkit-playsinline", "");
        video.preload = "auto";
        video.loop = false;
        video.style.cssText =
          "width:100%;height:100%;object-fit:contain;background:#04080d;display:block;";
        video.addEventListener("canplay", () => {
          this.flushPendingSeek();
        });
        video.addEventListener("loadedmetadata", () => {
          this.flushPendingSeek();
        });

        const onReady = () => {
          video.removeEventListener("canplaythrough", onReady);
          video.removeEventListener("loadeddata", onReady);
          // Clear stage and insert video
          this.stage.innerHTML = "";
          this.stage.appendChild(video);
          this.video = video;
          this.ready = true;
          if (this.message) this.message.hidden = true;
          resolve();
        };

        video.addEventListener("canplaythrough", onReady, { once: true });
        video.addEventListener("loadeddata", () => {
          setTimeout(() => { if (!this.ready) onReady(); }, 500);
        }, { once: true });

        video.onerror = () => {
          // Try next format
          this._tryLoad(sources, index + 1).then(resolve, reject);
        };

        video.load();
      });
    }

    update(frame, options) {
      if (!this.ready || !this.video) return;

      const playbackTimeSec = Number.isFinite(options?.playbackTimeSec)
        ? options.playbackTimeSec
        : 0;
      const isPlaying = options?.isPlaying === true;
      const forceSeek = options?.forceSeek === true;
      const playbackDurationSec = Number.isFinite(options?.playbackDurationSec)
        ? options.playbackDurationSec
        : this.playbackDurationSec;

      if (playbackDurationSec > 0) {
        this.playbackDurationSec = playbackDurationSec;
      }

      const videoDuration = this.video.duration || 1;
      const ratio = Math.min(Math.max(playbackTimeSec / Math.max(playbackDurationSec, 0.001), 0), 1);
      const targetSec = ratio * videoDuration;
      this._lastTargetSec = targetSec;

      const desiredPlaybackRate = Math.min(
        MAX_PLAYBACK_RATE,
        Math.max(MIN_PLAYBACK_RATE, videoDuration / Math.max(playbackDurationSec, 0.001)),
      );
      if (Math.abs(this.video.playbackRate - desiredPlaybackRate) > 0.005) {
        this.video.playbackRate = desiredPlaybackRate;
        this.video.defaultPlaybackRate = desiredPlaybackRate;
      }

      if (!isPlaying) {
        this.pauseVideo();
        if (forceSeek || Math.abs((this.video.currentTime || 0) - targetSec) > PAUSE_DRIFT_TOLERANCE_SEC) {
          this.seekTo(targetSec);
        }
        this._isPlaying = false;
        return;
      }

      const currentTime = this.video.currentTime || 0;
      const driftSec = Math.abs(currentTime - targetSec);
      if (forceSeek || driftSec > PLAY_DRIFT_TOLERANCE_SEC) {
        this.seekTo(targetSec);
      }
      this.playVideo();
      this._isPlaying = true;
    }

    resize() {
      // Video auto-resizes via CSS
    }

    seekTo(targetSec) {
      if (!this.video) return;
      const clamped = Math.min(Math.max(targetSec, 0), this.video.duration || targetSec || 0);
      if (!Number.isFinite(clamped)) return;
      if (this.video.readyState < 2) {
        this._pendingSeekSec = clamped;
        return;
      }
      if (Math.abs((this.video.currentTime || 0) - clamped) <= 0.01) return;
      this.video.currentTime = clamped;
      this._lastSeekSec = clamped;
      this._pendingSeekSec = null;
    }

    playVideo() {
      if (!this.video || !this.video.paused) return;
      const playPromise = this.video.play();
      if (playPromise && typeof playPromise.catch === "function") {
        playPromise.catch(() => {});
      }
    }

    pauseVideo() {
      if (!this.video || this.video.paused) return;
      this.video.pause();
    }

    flushPendingSeek() {
      if (!this.video || this._pendingSeekSec == null || this.video.readyState < 2) return;
      const pending = this._pendingSeekSec;
      this._pendingSeekSec = null;
      this.seekTo(pending);
    }
  }

  let instance = null;

  window.WorkWithAvatarPlayer = {
    init(options) {
      if (instance && instance.ready) return Promise.resolve(instance);
      instance = new AvatarPlayer();
      return instance.init(options).then(() => instance);
    },
    update(frame, options) {
      if (instance) instance.update(frame, options);
    },
    resize() {
      if (instance) instance.resize();
    },
  };
})();
