/**
 * avatar-player.js
 *
 * Lightweight avatar animation player.
 * Plays a pre-rendered video of the avatar animation in sync with the
 * session playback timeline. Works on both PWA and iOS (file://) builds.
 *
 * Supported formats (tried in order):
 *   1. avatar-animation.mp4  — generated by CI (render-frames.cjs + ffmpeg)
 *   2. avatar-animation.webm — generated locally via render-page.html in Chrome
 */
(() => {
  const VIDEO_SOURCES = [
    "media/avatar/avatar-animation.mp4",
    "media/avatar/avatar-animation.webm",
  ];

  class AvatarPlayer {
    constructor() {
      this.video = null;
      this.stage = null;
      this.message = null;
      this.ready = false;
      this.playbackDurationSec = 1;
      this._lastSeekSec = -1;
    }

    init({ stage, message }) {
      this.stage = stage;
      this.message = message;
      return this._tryLoad(VIDEO_SOURCES, 0);
    }

    _tryLoad(sources, index) {
      if (index >= sources.length) {
        // All formats failed
        if (this.message) {
          this.message.hidden = false;
          const t = this.message.querySelector("strong");
          const d = this.message.querySelector("em");
          if (t) t.textContent = "아바타 영상 로드 실패";
          if (d) d.textContent = "mp4 또는 webm 파일이 필요합니다.";
        }
        return Promise.reject(new Error("Avatar video not found (tried mp4, webm)"));
      }

      return new Promise((resolve, reject) => {
        const video = document.createElement("video");
        video.src = sources[index];
        video.muted = true;
        video.playsInline = true;
        video.setAttribute("playsinline", "");
        video.setAttribute("webkit-playsinline", "");
        video.preload = "auto";
        video.loop = false;
        video.style.cssText =
          "width:100%;height:100%;object-fit:contain;background:#04080d;display:block;";

        const onReady = () => {
          video.removeEventListener("canplaythrough", onReady);
          video.removeEventListener("loadeddata", onReady);
          // Clear stage and insert video
          this.stage.innerHTML = "";
          this.stage.appendChild(video);
          this.video = video;
          this.ready = true;
          if (this.message) this.message.hidden = true;
          resolve();
        };

        video.addEventListener("canplaythrough", onReady, { once: true });
        video.addEventListener("loadeddata", () => {
          setTimeout(() => { if (!this.ready) onReady(); }, 500);
        }, { once: true });

        video.onerror = () => {
          // Try next format
          this._tryLoad(sources, index + 1).then(resolve, reject);
        };

        video.load();
      });
    }

    update(frame, options) {
      if (!this.ready || !this.video) return;

      const playbackTimeSec = Number.isFinite(options?.playbackTimeSec)
        ? options.playbackTimeSec
        : 0;
      const playbackDurationSec = Number.isFinite(options?.playbackDurationSec)
        ? options.playbackDurationSec
        : this.playbackDurationSec;

      if (playbackDurationSec > 0) {
        this.playbackDurationSec = playbackDurationSec;
      }

      const videoDuration = this.video.duration || 1;
      const ratio = Math.min(playbackTimeSec / Math.max(playbackDurationSec, 0.001), 1);
      const targetSec = ratio * videoDuration;

      if (Math.abs(targetSec - this._lastSeekSec) > 0.02) {
        this.video.currentTime = targetSec;
        this._lastSeekSec = targetSec;
      }
    }

    resize() {
      // Video auto-resizes via CSS
    }
  }

  let instance = null;

  window.WorkWithAvatarPlayer = {
    init(options) {
      if (instance && instance.ready) return Promise.resolve(instance);
      instance = new AvatarPlayer();
      return instance.init(options).then(() => instance);
    },
    update(frame, options) {
      if (instance) instance.update(frame, options);
    },
    resize() {
      if (instance) instance.resize();
    },
  };
})();
